# Generated by Django 5.2.17 on 2026-10-02 06:03

import trips.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.CharField(default=trips.models.short_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inputs', models.JSONField()),
                ('result', models.JSONField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
